### ISSUE TITLE
Error with Textmaster\Client

### ISSUE THREAD

**Issue by jmleroux** [worldia/textmaster-api#69]
Hello,

I want to use textmaster-api to build a connector between Textmaster and Akeneo.

I just started the project and made a basic command to test the API calls:

```php
class ApiTestCommand extends ContainerAwareCommand
{
    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
            ->setName('pim:textmaster:api-test')
            ->setDescription('Test API calls');
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $client = $this->getContainer()->get('worldia.textmaster.api.client');
        $locales = $client->locales()->all();

        dump($locales);
    }
}
```

and declared my services in YAML:

```
    worldia.textmaster.api.httpclient:
        class: Textmaster\HttpClient\HttpClient
        arguments:
            - '%textmaster.api_key%'
            - '%textmaster.api_secret%'

    worldia.textmaster.api.client:
        class: Textmaster\Client
        arguments:
            - '@worldia.textmaster.api.httpclient'
            - '@event_dispatcher'
```

But the command does not work and i get this error:

```
[Textmaster\Exception\ErrorException]                                                                                                                                
  a:1:{s:4:"base";a:1:{i:0;s:127:"The URL you're requesting doesn't exist within the api. Make sure your URL begins with "http://api.textmaster.com/version_name"";}}  
```

I traced the error and it comes from here https://github.com/worldia/textmaster-api/blob/master/lib/Textmaster/HttpClient/HttpClient.php#L192
This method return this string : `/v1/clients/public/locales` and it seems that we expected `http://api.textmaster.com/v1/clients/public/locales`

Did i miss something in the configuration or in the instanciation ?

Best regards,
JM

**Comment by cdaguerre** [comment]
@jmleroux 
I guess there's a mistake [here](https://github.com/worldia/textmaster-api/blob/master/lib/Textmaster/HttpClient/HttpClient.php#L41). There shouldn't be a trailing `/clients`.
Could you either:
- remove `/clients`; or,
- instantiate the client with the following options (not tested): 
```yml
    worldia.textmaster.api.httpclient:
        class: Textmaster\HttpClient\HttpClient
        arguments:
            - '%textmaster.api_key%'
            - '%textmaster.api_secret%'
            - [ base_uri: 'http://api.textmaster.com/%s' ]
```
Or use `http://api.sandbox.textmaster.com/%s` whilst testing ;)
